#:schema https://json.schemastore.org/any.json

root = "."
tmp_dir = ".tmp/air"

[build]
cmd = "go build -o ./.tmp/air/docklane ./cmd/docklane"
entrypoint = [
  "./.tmp/air/docklane",
  "serve",
  "--listen=127.0.0.1:4646",
  "--database=./data/docklane-dev.db",
]
include_ext = ["go"]
include_dir = ["cmd", "internal"]
include_file = ["go.mod", "go.sum"]
exclude_dir = ["internal/webui/dist"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
delay = 300
stop_on_error = true
send_interrupt = true
kill_delay = "2s"

[log]
time = true

[misc]
clean_on_exit = true
